version: "3.3"
services:
  ac-clip-transformers:
    image: dockhardman/ac-clip:0.2.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ac-clip-transformers
    environment:
      - TRANSFORMERS_CACHE=./models/
      - DATASETS_ROOT=./data/
      - MODELS_ROOT=./models/
      - LOG_ROOT=./log/
    ports:
        - "51000:51000"
        - "51001:51001"
    networks:
        - ac-clip-network
    deploy:
      resources:
        limits:
          cpus: '2'
    volumes:
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - ./config.py:/app/config.py
        - ./executors:/app/executors
        - ./flows:/app/flows
        - ./helper:/app/helper
        - ./http_server.py:/app/http_server.py
        - ./data:/app/data
        - ./models:/app/models
        - ./log:/app/log
    tty: true

networks:
  ac-clip-network:
      name: ac-clip-network
